import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebar;